name: xse_wallet
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  url_launcher: ^5.0.2
  http: ^0.12.0
  path_provider: ^1.1.0
  web3dart: ^0.4.5
  pin_code_text_field: ^1.3.6
  
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/logo_full.png
   - assets/images/icon/icon_wallet_open.png
   - assets/images/icon/icon_wallet_close.png
   - assets/images/icon/icon_buy_open.png
   - assets/images/icon/icon_buy_close.png
   - assets/images/icon/icon_sell_open.png
   - assets/images/icon/icon_sell_close.png
   - assets/images/icon/icon_offers_open.png
   - assets/images/icon/icon_offers_close.png
   - assets/images/icon/icon_account_open.png
   - assets/images/icon/icon_account_close.png

   - assets/images/bg_line.png
   - assets/images/s_logo.png
   - assets/images/btn_plus.png
   - assets/images/qrcode.png
   - assets/images/ref_logo.png

   - assets/images/logo/btc.png
   - assets/images/logo/eth.png
   - assets/images/logo/token.png

   - assets/images/icon/btn_up.png
   - assets/images/icon/btn_down.png

   - assets/images/onboard/p01.png
   - assets/images/onboard/p02.png
   - assets/images/onboard/p03.png
   - assets/images/onboard/p04.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LeagueGothic
      fonts:
        - asset: fonts/leaguegothic-regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
